{
 "title": "NEWS2 Dashboard",
 "description": "Example dashboard for NEWS2 data",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "[QA use case] Bed assignment/registration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "[All Users] Bed Registration",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kafka_consumer_correct_bed_registration{topic=\"processed-topic\"}",
     "legendFormat": " {{userid}}"
    }
   ]
  },
  {
   "title": "[All Users] Bed Registration",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "kafka_consumer_correct_bed_registration{topic=\"prink-topic\"}",
     "legendFormat": " {{userid}}"
    }
   ]
  },
  { "title": "Patient Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "type": "timeseries",
   "description": "Patient 10342",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "kafka_consumer_bps{topic=\"prink-topic\", userid=\"0376467\"}",
     "legendFormat": "BPS"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Patient 10342",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_bps{topic=\"prink-topic\", userid=\"0376467\"}",
     "legendFormat": "BPS"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Patient 10342",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "kafka_consumer_resp{topic=\"prink-topic\", userid=\"0376467\"}",
     "legendFormat": "RESP"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Patient 10342",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_resp{topic=\"prink-topic\", userid=\"0376467\"}",
     "legendFormat": "RESP"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Patient 10342",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "kafka_consumer_pulse{topic=\"prink-topic\", userid=\"0376467\"}",
     "legendFormat": "PULSE"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Patient 10342",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_pulse{topic=\"prink-topic\", userid=\"0376467\"}",
     "legendFormat": "PULSE"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Patient 10342",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "kafka_consumer_temp{topic=\"prink-topic\", userid=\"0376467\"}",
     "legendFormat": "TEMP"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Patient 10342",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_temp{topic=\"prink-topic\", userid=\"0376467\"}",
     "legendFormat": "TEMP"
    }
   ]
  },
  { "title": "Unit Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 14, "x": 10, "y": 47 },
   "options": {
    "content": "# Patient Monitoring System\n# >> Example Care Unit <<    \n\n"
   }
  },
  {
   "title": "NEWS2 Overview",
   "type": "gauge",
   "description": "Sum of physiological parameter scores.",
   "gridPos": { "h": 17, "w": 13, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_bps{topic=\"processed-topic\"} + kafka_consumer_resp{topic=\"processed-topic\"} + kafka_consumer_pulse{topic=\"processed-topic\"} + kafka_consumer_temp{topic=\"processed-topic\"}",
     "legendFormat": "uid {{userid}}"
    }
   ]
  },
  {
   "title": "Information Loss",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 7, "x": 13, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_infoloss{topic=\"prink-topic\"}",
     "legendFormat": "uid {{userid}}"
    }
   ]
  },
  {
   "title": "Max.",
   "type": "stat",
   "description": "Maximum Infoloss",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_consumer_infoloss{topic=\"prink-topic\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. Infoloss",
   "type": "stat",
   "description": "Average Infoloss",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_consumer_infoloss{topic=\"prink-topic\"}) / 20",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min. ",
   "type": "stat",
   "description": "Average Infoloss",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(kafka_consumer_infoloss{topic=\"prink-topic\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Comparison NEWS2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "[All Users] NEWS2",
   "type": "bargauge",
   "description": "Sum of physiological parameter scores.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_bps{topic=\"processed-topic\"} + kafka_consumer_resp{topic=\"processed-topic\"} + kafka_consumer_pulse{topic=\"processed-topic\"} + kafka_consumer_temp{topic=\"processed-topic\"}",
     "legendFormat": "uid {{userid}}"
    }
   ]
  },
  {
   "title": "[All Users] NEWS2 ANON",
   "type": "bargauge",
   "description": "Sum of physiological parameter scores.",
   "gridPos": { "h": 15, "w": 8, "x": 12, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_bps{topic=\"prink-topic\"} + kafka_consumer_resp{topic=\"prink-topic\"} + kafka_consumer_pulse{topic=\"prink-topic\"} + kafka_consumer_temp{topic=\"prink-topic\"}",
     "legendFormat": "uid {{userid}}"
    }
   ]
  },
  {
   "title": "Information Loss",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 4, "x": 20, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_infoloss{topic=\"prink-topic\"}",
     "legendFormat": "uid {{userid}}"
    }
   ]
  },
  {
   "title": "[All Users] PULSE",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_pulse{topic=\"processed-topic\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "[All Users] PULSE",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_pulse{topic=\"prink-topic\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "User 10342: NEWS2",
   "type": "timeseries",
   "description": "Sum of physiological parameter scores for userid = 10342.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "kafka_consumer_bps{userid=\"10342\", topic=\"processed-topic\"} + kafka_consumer_pulse{userid=\"10342\", topic=\"processed-topic\"} + kafka_consumer_resp{userid=\"10342\", topic=\"processed-topic\"} + kafka_consumer_temp{userid=\"10342\", topic=\"processed-topic\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "User 10342: NEWS2 ANON",
   "type": "timeseries",
   "description": "Sum of physiological parameter scores for userid = 10342.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "targets": [
    {
     "expr": "kafka_consumer_bps{userid=\"10342\", topic=\"prink-topic\"} + kafka_consumer_pulse{userid=\"10342\", topic=\"prink-topic\"} + kafka_consumer_resp{userid=\"10342\", topic=\"prink-topic\"} + kafka_consumer_temp{userid=\"10342\", topic=\"prink-topic\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "User 10342: Physiological Parameters ",
   "type": "bargauge",
   "description": "userid = 10342",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 97 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_bps{topic=\"processed-topic\", userid=\"10342\"}",
     "legendFormat": "systolic blood pressure"
    },
    {
     "expr": "kafka_consumer_pulse{topic=\"processed-topic\", userid=\"10342\"}",
     "legendFormat": "pulse"
    },
    {
     "expr": "kafka_consumer_resp{topic=\"processed-topic\", userid=\"10342\"}",
     "legendFormat": "respiration rate"
    },
    {
     "expr": "kafka_consumer_temp{topic=\"processed-topic\", userid=\"10342\"}",
     "legendFormat": "temperature"
    }
   ]
  },
  {
   "title": "User 10342: Physiological Parameters ANON",
   "type": "bargauge",
   "description": "userid = 10342",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 97 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_bps{userid=\"10342\", topic=\"prink-topic\"}",
     "legendFormat": "systolic blood pressure"
    },
    {
     "expr": "kafka_consumer_pulse{userid=\"10342\", topic=\"prink-topic\"}",
     "legendFormat": "pulse"
    },
    {
     "expr": "kafka_consumer_resp{userid=\"10342\", topic=\"prink-topic\"}",
     "legendFormat": "respiration rate"
    },
    {
     "expr": "kafka_consumer_temp{userid=\"10342\", topic=\"prink-topic\"}",
     "legendFormat": "temperature"
    }
   ]
  }
 ]
}