{
 "title": "NEWS2 Dashboard",
 "description": "Example dashboard for NEWS2 data",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "[QA use case] Distinct parameters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "[All Users] Parameter Check",
   "type": "heatmap",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "changes(kafka_consumer_recordid{topic=\"processed-topic\", waveformlabel=\"I\"}[5m])",
     "legendFormat": "{{userid}}"
    }
   ]
  },
  {
   "title": "[All Users] Parameter Check",
   "type": "heatmap",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "changes(kafka_consumer_recordid{topic=\"processed-topic\", waveformlabel=\"I\"}[5m])",
     "legendFormat": "{{userid}}"
    }
   ]
  },
  {
   "title": "[One User] Parameter Check",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "changes(kafka_consumer_recordid{topic=\"processed-topic\", waveformlabel!=\"\", userid=\"0311047\"}[5m])",
     "legendFormat": "{{waveformlabel}}"
    }
   ]
  },
  {
   "title": "[One User] Parameter Check",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "changes(kafka_consumer_recordid{topic=\"processed-topic\", waveformlabel!=\"\", userid=\"0311047\"}[5m])",
     "legendFormat": "{{waveformlabel}}"
    }
   ]
  },
  {
   "title": "[One User] Updates to distinct waveform parameters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "changes(kafka_consumer_recordid{topic=\"processed-topic\", waveformlabel!=\"\", userid=\"0311047\"}[5m])",
     "legendFormat": "{{waveformlabel}}"
    }
   ]
  },
  {
   "title": "[One User] Updates to distinct waveform parameters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "changes(kafka_consumer_recordid{topic=\"processed-topic\", waveformlabel!=\"\", userid=\"0311047\"}[5m])",
     "legendFormat": "{{waveformlabel}}"
    }
   ]
  },
  {
   "title": "[All Users] #Updates to all waveform parameters",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "changes(kafka_consumer_recordid{topic=\"processed-topic\", waveformlabel=\"I\"}[5m])",
     "legendFormat": "{{userid}}"
    }
   ]
  },
  {
   "title": "[All Users] #Updates to all waveform parameters",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "changes(kafka_consumer_recordid{topic=\"processed-topic\", waveformlabel=\"I\"}[5m])",
     "legendFormat": "{{userid}}"
    }
   ]
  },
  {
   "title": "[QA use case] Bed assignment/registration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 }
  },
  {
   "title": "[All Users] Bed Registration",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "kafka_consumer_correct_bed_registration{topic=\"processed-topic\"}",
     "legendFormat": " {{userid}}"
    }
   ]
  },
  {
   "title": "[All Users] Bed Registration",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "kafka_consumer_correct_bed_registration{topic=\"prink-topic\"}",
     "legendFormat": " {{userid}}"
    }
   ]
  },
  {
   "title": "Patient Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "type": "timeseries",
     "description": "Patient 10342",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 197 },
     "targets": [
      {
       "expr": "kafka_consumer_bps{topic=\"prink-topic\", userid=\"0376467\"}",
       "legendFormat": "BPS"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Patient 10342",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 197 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_consumer_bps{topic=\"prink-topic\", userid=\"0376467\"}",
       "legendFormat": "BPS"
      }
     ]
    },
    {
     "type": "timeseries",
     "description": "Patient 10342",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 205 },
     "targets": [
      {
       "expr": "kafka_consumer_resp{topic=\"prink-topic\", userid=\"0376467\"}",
       "legendFormat": "RESP"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Patient 10342",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 205 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_consumer_resp{topic=\"prink-topic\", userid=\"0376467\"}",
       "legendFormat": "RESP"
      }
     ]
    },
    {
     "type": "timeseries",
     "description": "Patient 10342",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 213 },
     "targets": [
      {
       "expr": "kafka_consumer_pulse{topic=\"prink-topic\", userid=\"0376467\"}",
       "legendFormat": "PULSE"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Patient 10342",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 213 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_consumer_pulse{topic=\"prink-topic\", userid=\"0376467\"}",
       "legendFormat": "PULSE"
      }
     ]
    },
    {
     "type": "timeseries",
     "description": "Patient 10342",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 221 },
     "targets": [
      {
       "expr": "kafka_consumer_temp{topic=\"prink-topic\", userid=\"0376467\"}",
       "legendFormat": "TEMP"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Patient 10342",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 221 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_consumer_temp{topic=\"prink-topic\", userid=\"0376467\"}",
       "legendFormat": "TEMP"
      }
     ]
    }
   ]
  },
  {
   "title": "Unit Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 14, "x": 10, "y": 230 },
     "options": {
      "content": "# Patient Monitoring System\n# >> Example Care Unit <<    \n\n"
     }
    },
    {
     "title": "NEWS2 Overview",
     "type": "gauge",
     "description": "Sum of physiological parameter scores.",
     "gridPos": { "h": 17, "w": 11, "x": 0, "y": 233 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "kafka_consumer_bps{topic=\"processed-topic\"} + kafka_consumer_resp{topic=\"processed-topic\"} + kafka_consumer_pulse{topic=\"processed-topic\"} + kafka_consumer_temp{topic=\"processed-topic\"}",
       "legendFormat": "uid {{userid}}"
      }
     ]
    },
    {
     "title": "Information Loss",
     "type": "bargauge",
     "gridPos": { "h": 17, "w": 8, "x": 12, "y": 233 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "group by(userid) (kafka_consumer_infoloss{topic=\"prink-topic\"})",
       "legendFormat": "{{userid}}"
      }
     ]
    },
    {
     "title": "Max.",
     "type": "stat",
     "description": "Maximum Infoloss",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 233 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(kafka_consumer_infoloss{topic=\"prink-topic\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg. Infoloss",
     "type": "stat",
     "description": "Average Infoloss",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 238 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(topic) (kafka_consumer_infoloss{topic=\"prink-topic\"}) / 20",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Min. ",
     "type": "stat",
     "description": "Average Infoloss",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 245 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min(kafka_consumer_infoloss{topic=\"prink-topic\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Comparison NEWS2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "[All Users] NEWS2",
   "type": "bargauge",
   "description": "Sum of physiological parameter scores.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_bps{topic=\"processed-topic\"} + kafka_consumer_resp{topic=\"processed-topic\"} + kafka_consumer_pulse{topic=\"processed-topic\"} + kafka_consumer_temp{topic=\"processed-topic\"}",
     "legendFormat": "uid {{userid}}"
    }
   ]
  },
  {
   "title": "[All Users] NEWS2 ANON",
   "type": "bargauge",
   "description": "Sum of physiological parameter scores.",
   "gridPos": { "h": 15, "w": 8, "x": 12, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_bps{topic=\"prink-topic\"} + kafka_consumer_resp{topic=\"prink-topic\"} + kafka_consumer_pulse{topic=\"prink-topic\"} + kafka_consumer_temp{topic=\"prink-topic\"}",
     "legendFormat": "uid {{userid}}"
    }
   ]
  },
  {
   "title": "Information Loss",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 4, "x": 20, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_infoloss{topic=\"prink-topic\"}",
     "legendFormat": "uid {{userid}}"
    }
   ]
  },
  {
   "title": "[All Users] PULSE",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by(waveformlabel) (kafka_consumer_pulse{topic=\"processed-topic\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "[All Users] PULSE",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by(waveformlabel) (kafka_consumer_pulse{topic=\"prink-topic\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "User 10342: NEWS2",
   "type": "timeseries",
   "description": "Sum of physiological parameter scores for userid = 10342.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "kafka_consumer_bps{userid=\"10342\", topic=\"processed-topic\"} + kafka_consumer_pulse{userid=\"10342\", topic=\"processed-topic\"} + kafka_consumer_resp{userid=\"10342\", topic=\"processed-topic\"} + kafka_consumer_temp{userid=\"10342\", topic=\"processed-topic\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "User 10342: NEWS2 ANON",
   "type": "timeseries",
   "description": "Sum of physiological parameter scores for userid = 10342.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "expr": "kafka_consumer_bps{userid=\"10342\", topic=\"prink-topic\"} + kafka_consumer_pulse{userid=\"10342\", topic=\"prink-topic\"} + kafka_consumer_resp{userid=\"10342\", topic=\"prink-topic\"} + kafka_consumer_temp{userid=\"10342\", topic=\"prink-topic\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "User 10342: Physiological Parameters ",
   "type": "bargauge",
   "description": "userid = 10342",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 96 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_bps{topic=\"processed-topic\", userid=\"10342\"}",
     "legendFormat": "systolic blood pressure"
    },
    {
     "expr": "kafka_consumer_pulse{topic=\"processed-topic\", userid=\"10342\"}",
     "legendFormat": "pulse"
    },
    {
     "expr": "kafka_consumer_resp{topic=\"processed-topic\", userid=\"10342\"}",
     "legendFormat": "respiration rate"
    },
    {
     "expr": "kafka_consumer_temp{topic=\"processed-topic\", userid=\"10342\"}",
     "legendFormat": "temperature"
    }
   ]
  },
  {
   "title": "User 10342: Physiological Parameters ANON",
   "type": "bargauge",
   "description": "userid = 10342",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 96 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_bps{userid=\"10342\", topic=\"prink-topic\"}",
     "legendFormat": "systolic blood pressure"
    },
    {
     "expr": "kafka_consumer_pulse{userid=\"10342\", topic=\"prink-topic\"}",
     "legendFormat": "pulse"
    },
    {
     "expr": "kafka_consumer_resp{userid=\"10342\", topic=\"prink-topic\"}",
     "legendFormat": "respiration rate"
    },
    {
     "expr": "kafka_consumer_temp{userid=\"10342\", topic=\"prink-topic\"}",
     "legendFormat": "temperature"
    }
   ]
  }
 ]
}