{
 "title": "NEWS2 Dashboard",
 "description": "Example dashboard for NEWS2 data",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "[Prediction use case] Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "[QA use case] Distinct parameters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "[All Users] #Updates to all waveform parameters",
     "type": "heatmap",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "changes(kafka_consumer_recordid{topic=\"processed-topic\", waveformlabel=\"I\"}[5m])",
       "legendFormat": "{{userid}}"
      }
     ]
    },
    {
     "title": "[All Users] #Updates to all waveform parameters",
     "type": "heatmap",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "changes(kafka_consumer_recordid{topic=\"processed-topic\", waveformlabel=\"I\"}[5m])",
       "legendFormat": "{{userid}}"
      }
     ]
    },
    {
     "title": "[One User] Parameter Check",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "changes(kafka_consumer_recordid{topic=\"processed-topic\", waveformlabel!=\"\", userid=\"0311319\"}[5m])",
       "legendFormat": "{{waveformlabel}}"
      }
     ]
    },
    {
     "title": "[One User] Parameter Check",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 52 },
     "targets": [
      {
       "expr": "changes(kafka_consumer_recordid{topic=\"prink-topic\", waveformlabel!=\"\", userid=\"0311319\"}[5m])",
       "legendFormat": "{{waveformlabel}}"
      }
     ]
    },
    {
     "title": "[One User] Updates to distinct waveform parameters",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 64 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "changes(kafka_consumer_recordid{topic=\"processed-topic\", waveformlabel!=\"\", userid=\"0311319\"}[5m])",
       "legendFormat": "{{waveformlabel}}"
      }
     ]
    },
    {
     "title": "[One User] Updates to distinct waveform parameters",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 64 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "changes(kafka_consumer_recordid{topic=\"prink-topic\", waveformlabel!=\"\", userid=\"0311319\"}[5m])",
       "legendFormat": "{{waveformlabel}}"
      }
     ]
    }
   ]
  },
  {
   "title": "[QA use case] Bed assignment/registration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "[All Users] Bed Registration",
     "type": "heatmap",
     "gridPos": { "h": 24, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "kafka_consumer_correct_bed_registration{topic=\"processed-topic\"}",
       "legendFormat": " {{userid}}"
      }
     ]
    },
    {
     "title": "[All Users] Bed Registration",
     "type": "heatmap",
     "gridPos": { "h": 24, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "kafka_consumer_correct_bed_registration{topic=\"prink-topic\"}",
       "legendFormat": " {{userid}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Patient Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "type": "timeseries",
     "description": "Patient 0311319",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 147 },
     "targets": [
      {
       "expr": "max by(userid) (kafka_consumer_bps{topic=\"prink-topic\", userid=\"0311319\"})",
       "legendFormat": "BPS"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Patient 10342",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 147 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(userid) (kafka_consumer_bps{topic=\"prink-topic\", userid=\"0311319\"})",
       "legendFormat": "BPS"
      }
     ]
    },
    {
     "type": "timeseries",
     "description": "Patient 10342",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 155 },
     "targets": [
      {
       "expr": "max by(userid) (kafka_consumer_resp{topic=\"prink-topic\", userid=\"0311319\"})",
       "legendFormat": "RESP"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Patient 10342",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 155 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(userid) (kafka_consumer_resp{topic=\"prink-topic\", userid=\"0311319\"})",
       "legendFormat": "RESP"
      }
     ]
    },
    {
     "type": "timeseries",
     "description": "Patient 10342",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 163 },
     "targets": [
      {
       "expr": "max by(userid) (kafka_consumer_pulse{topic=\"prink-topic\", userid=\"0311319\"})",
       "legendFormat": "PULSE"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Patient 10342",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 163 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(userid) (kafka_consumer_pulse{topic=\"prink-topic\", userid=\"0311319\"})",
       "legendFormat": "PULSE"
      }
     ]
    },
    {
     "type": "timeseries",
     "description": "Patient 10342",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 171 },
     "targets": [
      {
       "expr": "max by(userid) (kafka_consumer_temp{topic=\"prink-topic\", userid=\"0311319\"})",
       "legendFormat": "TEMP"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Patient 10342",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 171 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(userid) (kafka_consumer_temp{topic=\"prink-topic\", userid=\"0311319\"})",
       "legendFormat": "TEMP"
      }
     ]
    }
   ]
  },
  {
   "title": "Unit Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 14, "x": 10, "y": 180 },
     "options": {
      "content": "# Patient Monitoring System\n# >> Example Care Unit <<    \n\n"
     }
    },
    {
     "title": "NEWS2 Overview",
     "type": "gauge",
     "description": "Sum of physiological parameter scores.",
     "gridPos": { "h": 17, "w": 12, "x": 0, "y": 183 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max by (userid) (kafka_consumer_bps{topic=\"processed-topic\"}) + max by (userid) (kafka_consumer_resp{topic=\"processed-topic\"}) + max by (userid) (kafka_consumer_pulse{topic=\"processed-topic\"}) + max by (userid) (kafka_consumer_temp{topic=\"processed-topic\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Information Loss",
     "type": "bargauge",
     "gridPos": { "h": 17, "w": 8, "x": 12, "y": 183 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(userid) (kafka_consumer_infoloss{topic=\"prink-topic\"})",
       "legendFormat": "{{userid}}"
      }
     ]
    },
    {
     "title": "Max.",
     "type": "stat",
     "description": "Maximum Infoloss",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 183 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(waveformlabel) (max by(userid) (max(kafka_consumer_infoloss{topic=\"prink-topic\"})))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg. Infoloss",
     "type": "stat",
     "description": "Average Infoloss",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 188 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(waveformlabel) (max by(userid) (kafka_consumer_infoloss{topic=\"prink-topic\"})) / 20",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Min. ",
     "type": "stat",
     "description": "Average Infoloss",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 195 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(waveformlabel) (max by(userid) (min(kafka_consumer_infoloss{topic=\"prink-topic\"})))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Comparison NEWS2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "[All Users] NEWS2",
   "type": "bargauge",
   "description": "Sum of physiological parameter scores.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (userid) (kafka_consumer_bps{topic=\"processed-topic\"}) + max by (userid) (kafka_consumer_resp{topic=\"processed-topic\"}) + max by (userid) (kafka_consumer_pulse{topic=\"processed-topic\"}) + max by (userid) (kafka_consumer_temp{topic=\"processed-topic\"})",
     "legendFormat": "{{userid}}"
    }
   ]
  },
  {
   "title": "[All Users] NEWS2 ANON",
   "type": "bargauge",
   "description": "Sum of physiological parameter scores.",
   "gridPos": { "h": 15, "w": 8, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(userid) (kafka_consumer_bps{topic=\"prink-topic\"}) + max by(userid) (kafka_consumer_resp{topic=\"prink-topic\"}) + max by(userid) (kafka_consumer_pulse{topic=\"prink-topic\"}) + max by(userid) (kafka_consumer_temp{topic=\"prink-topic\"})",
     "legendFormat": "{{userid}}"
    }
   ]
  },
  {
   "title": "Information Loss",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(userid) (kafka_consumer_infoloss{topic=\"prink-topic\"})",
     "legendFormat": "{{userid}}"
    }
   ]
  },
  {
   "title": "[All Users] PULSE",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(userid) (kafka_consumer_pulse{topic=\"processed-topic\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "[All Users] PULSE",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(userid) (kafka_consumer_pulse{topic=\"prink-topic\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "User 0311319: NEWS2",
   "type": "timeseries",
   "description": "Sum of physiological parameter scores for userid = 0311319.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "max by(userid) (kafka_consumer_bps{userid=\"0311319\", topic=\"processed-topic\"}) + max by(userid) (kafka_consumer_pulse{userid=\"0311319\", topic=\"processed-topic\"}) + max by(userid) (kafka_consumer_resp{userid=\"0311319\", topic=\"processed-topic\"}) + max by(userid) (kafka_consumer_temp{userid=\"0311319\", topic=\"processed-topic\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "User 0311319: NEWS2",
   "type": "timeseries",
   "description": "Sum of physiological parameter scores for userid = 0311319.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "max by(userid) (kafka_consumer_bps{userid=\"0311319\", topic=\"prink-topic\"}) + max by(userid) (kafka_consumer_pulse{userid=\"0311319\", topic=\"prink-topic\"}) + max by(userid) (kafka_consumer_resp{userid=\"0311319\", topic=\"prink-topic\"}) + max by(userid) (kafka_consumer_temp{userid=\"0311319\", topic=\"prink-topic\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "User 0311319: Physiological Parameters ",
   "type": "bargauge",
   "description": "userid = 0311319",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(userid) (kafka_consumer_bps{topic=\"processed-topic\", userid=\"0311319\"})",
     "legendFormat": "systolic blood pressure"
    },
    {
     "expr": "max by(userid) (kafka_consumer_pulse{topic=\"processed-topic\", userid=\"0311319\"})",
     "legendFormat": "pulse"
    },
    {
     "expr": "max by(userid) (kafka_consumer_resp{topic=\"processed-topic\", userid=\"0311319\"})",
     "legendFormat": "respiration rate"
    },
    {
     "expr": "max by(userid) (kafka_consumer_temp{topic=\"processed-topic\", userid=\"0311319\"})",
     "legendFormat": "temperature"
    }
   ]
  },
  {
   "title": "User 0311319: Physiological Parameters ",
   "type": "bargauge",
   "description": "userid = 0311319",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(userid) (kafka_consumer_bps{topic=\"prink-topic\", userid=\"0311319\"})",
     "legendFormat": "systolic blood pressure"
    },
    {
     "expr": "max by(userid) (kafka_consumer_pulse{topic=\"prink-topic\", userid=\"0311319\"})",
     "legendFormat": "pulse"
    },
    {
     "expr": "max by(userid) (kafka_consumer_resp{topic=\"prink-topic\", userid=\"0311319\"})",
     "legendFormat": "respiration rate"
    },
    {
     "expr": "max by(userid) (kafka_consumer_temp{topic=\"prink-topic\", userid=\"0311319\"})",
     "legendFormat": "temperature"
    }
   ]
  }
 ]
}