{
 "title": "NEWS2 Dashboard",
 "description": "Example dashboard for NEWS2 data",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "[QA use case] Distinct parameters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "[All Users] #Updates to all waveform parameters",
   "type": "heatmap",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "changes(kafka_consumer_recordid{topic=\"processed-topic\", waveformlabel=\"I\"}[5m])",
     "legendFormat": "{{userid}}"
    }
   ]
  },
  {
   "title": "[All Users] #Updates to all waveform parameters",
   "type": "heatmap",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "changes(kafka_consumer_recordid{topic=\"processed-topic\", waveformlabel=\"I\"}[5m])",
     "legendFormat": "{{userid}}"
    }
   ]
  },
  {
   "title": "[One User] Parameter Check",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "changes(kafka_consumer_recordid{topic=\"processed-topic\", waveformlabel!=\"\", userid=\"0311047\"}[5m])",
     "legendFormat": "{{waveformlabel}}"
    }
   ]
  },
  {
   "title": "[One User] Parameter Check",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "changes(kafka_consumer_recordid{topic=\"processed-topic\", waveformlabel!=\"\", userid=\"0311047\"}[5m])",
     "legendFormat": "{{waveformlabel}}"
    }
   ]
  },
  {
   "title": "[One User] Updates to distinct waveform parameters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "changes(kafka_consumer_recordid{topic=\"processed-topic\", waveformlabel!=\"\", userid=\"0311047\"}[5m])",
     "legendFormat": "{{waveformlabel}}"
    }
   ]
  },
  {
   "title": "[One User] Updates to distinct waveform parameters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "changes(kafka_consumer_recordid{topic=\"processed-topic\", waveformlabel!=\"\", userid=\"0311047\"}[5m])",
     "legendFormat": "{{waveformlabel}}"
    }
   ]
  },
  {
   "title": "[QA use case] Bed assignment/registration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "[All Users] Bed Registration",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "kafka_consumer_correct_bed_registration{topic=\"processed-topic\"}",
       "legendFormat": " {{userid}}"
      }
     ]
    },
    {
     "title": "[All Users] Bed Registration",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 52 },
     "targets": [
      {
       "expr": "kafka_consumer_correct_bed_registration{topic=\"prink-topic\"}",
       "legendFormat": " {{userid}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Patient Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "type": "timeseries",
     "description": "Patient 10342",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 247 },
     "targets": [
      {
       "expr": "kafka_consumer_bps{topic=\"prink-topic\", userid=\"0376467\"}",
       "legendFormat": "BPS"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Patient 10342",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 247 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_consumer_bps{topic=\"prink-topic\", userid=\"0376467\"}",
       "legendFormat": "BPS"
      }
     ]
    },
    {
     "type": "timeseries",
     "description": "Patient 10342",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 255 },
     "targets": [
      {
       "expr": "kafka_consumer_resp{topic=\"prink-topic\", userid=\"0376467\"}",
       "legendFormat": "RESP"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Patient 10342",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 255 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_consumer_resp{topic=\"prink-topic\", userid=\"0376467\"}",
       "legendFormat": "RESP"
      }
     ]
    },
    {
     "type": "timeseries",
     "description": "Patient 10342",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 263 },
     "targets": [
      {
       "expr": "kafka_consumer_pulse{topic=\"prink-topic\", userid=\"0376467\"}",
       "legendFormat": "PULSE"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Patient 10342",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 263 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_consumer_pulse{topic=\"prink-topic\", userid=\"0376467\"}",
       "legendFormat": "PULSE"
      }
     ]
    },
    {
     "type": "timeseries",
     "description": "Patient 10342",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 271 },
     "targets": [
      {
       "expr": "kafka_consumer_temp{topic=\"prink-topic\", userid=\"0376467\"}",
       "legendFormat": "TEMP"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Patient 10342",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 271 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_consumer_temp{topic=\"prink-topic\", userid=\"0376467\"}",
       "legendFormat": "TEMP"
      }
     ]
    }
   ]
  },
  {
   "title": "Unit Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 14, "x": 10, "y": 280 },
     "options": {
      "content": "# Patient Monitoring System\n# >> Example Care Unit <<    \n\n"
     }
    },
    {
     "title": "NEWS2 Overview",
     "type": "gauge",
     "description": "Sum of physiological parameter scores.",
     "gridPos": { "h": 17, "w": 11, "x": 0, "y": 283 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "kafka_consumer_bps{topic=\"processed-topic\"} + kafka_consumer_resp{topic=\"processed-topic\"} + kafka_consumer_pulse{topic=\"processed-topic\"} + kafka_consumer_temp{topic=\"processed-topic\"}",
       "legendFormat": "uid {{userid}}"
      }
     ]
    },
    {
     "title": "Information Loss",
     "type": "bargauge",
     "gridPos": { "h": 17, "w": 8, "x": 12, "y": 283 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "group by(userid) (kafka_consumer_infoloss{topic=\"prink-topic\"})",
       "legendFormat": "{{userid}}"
      }
     ]
    },
    {
     "title": "Max.",
     "type": "stat",
     "description": "Maximum Infoloss",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 283 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(kafka_consumer_infoloss{topic=\"prink-topic\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg. Infoloss",
     "type": "stat",
     "description": "Average Infoloss",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 288 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(topic) (kafka_consumer_infoloss{topic=\"prink-topic\"}) / 20",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Min. ",
     "type": "stat",
     "description": "Average Infoloss",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 295 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min(kafka_consumer_infoloss{topic=\"prink-topic\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Comparison NEWS2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "[All Users] NEWS2",
     "type": "bargauge",
     "description": "Sum of physiological parameter scores.",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 117 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max by (userid) (kafka_consumer_bps{topic=\"processed-topic\"}) + max by (userid) (kafka_consumer_resp{topic=\"processed-topic\"}) + max by (userid) (kafka_consumer_pulse{topic=\"processed-topic\"}) + max by (userid) (kafka_consumer_temp{topic=\"processed-topic\"})",
       "legendFormat": "{{userid}}"
      }
     ]
    },
    {
     "title": "[All Users] NEWS2 ANON",
     "type": "bargauge",
     "description": "Sum of physiological parameter scores.",
     "gridPos": { "h": 15, "w": 8, "x": 12, "y": 117 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(userid) (kafka_consumer_bps{topic=\"prink-topic\"}) + max by(userid) (kafka_consumer_resp{topic=\"prink-topic\"}) + max by(userid) (kafka_consumer_pulse{topic=\"prink-topic\"}) + max by(userid) (kafka_consumer_temp{topic=\"prink-topic\"})",
       "legendFormat": "{{userid}}"
      }
     ]
    },
    {
     "title": "Information Loss",
     "type": "bargauge",
     "gridPos": { "h": 15, "w": 4, "x": 20, "y": 117 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(userid) (kafka_consumer_infoloss{topic=\"prink-topic\"})",
       "legendFormat": "{{userid}}"
      }
     ]
    },
    {
     "title": "[All Users] PULSE",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(userid) (kafka_consumer_pulse{topic=\"processed-topic\"})",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "[All Users] PULSE",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(userid) (kafka_consumer_pulse{topic=\"prink-topic\"})",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "User 0311047: NEWS2",
     "type": "timeseries",
     "description": "Sum of physiological parameter scores for userid = 0311047.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
     "targets": [
      {
       "expr": "max by(userid) (kafka_consumer_bps{userid=\"0311047\", topic=\"processed-topic\"}) + max by(userid) (kafka_consumer_pulse{userid=\"0311047\", topic=\"processed-topic\"}) + max by(userid) (kafka_consumer_resp{userid=\"0311047\", topic=\"processed-topic\"}) + max by(userid) (kafka_consumer_temp{userid=\"0311047\", topic=\"processed-topic\"})",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "User 0311047: NEWS2",
     "type": "timeseries",
     "description": "Sum of physiological parameter scores for userid = 0311047.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
     "targets": [
      {
       "expr": "max by(userid) (kafka_consumer_bps{userid=\"0311047\", topic=\"prink-topic\"}) + max by(userid) (kafka_consumer_pulse{userid=\"0311047\", topic=\"prink-topic\"}) + max by(userid) (kafka_consumer_resp{userid=\"0311047\", topic=\"prink-topic\"}) + max by(userid) (kafka_consumer_temp{userid=\"0311047\", topic=\"prink-topic\"})",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "User 0311047: Physiological Parameters ",
     "type": "bargauge",
     "description": "userid = 0311047",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 146 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(userid) (kafka_consumer_bps{topic=\"processed-topic\", userid=\"0311047\"})",
       "legendFormat": "systolic blood pressure"
      },
      {
       "expr": "max by(userid) (kafka_consumer_pulse{topic=\"processed-topic\", userid=\"0311047\"})",
       "legendFormat": "pulse"
      },
      {
       "expr": "max by(userid) (kafka_consumer_resp{topic=\"processed-topic\", userid=\"0311047\"})",
       "legendFormat": "respiration rate"
      },
      {
       "expr": "max by(userid) (kafka_consumer_temp{topic=\"processed-topic\", userid=\"0311047\"})",
       "legendFormat": "temperature"
      }
     ]
    },
    {
     "title": "User 0311047: Physiological Parameters ",
     "type": "bargauge",
     "description": "userid = 0311047",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 146 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(userid) (kafka_consumer_bps{topic=\"prink-topic\", userid=\"0311047\"})",
       "legendFormat": "systolic blood pressure"
      },
      {
       "expr": "max by(userid) (kafka_consumer_pulse{topic=\"prink-topic\", userid=\"0311047\"})",
       "legendFormat": "pulse"
      },
      {
       "expr": "max by(userid) (kafka_consumer_resp{topic=\"prink-topic\", userid=\"0311047\"})",
       "legendFormat": "respiration rate"
      },
      {
       "expr": "max by(userid) (kafka_consumer_temp{topic=\"prink-topic\", userid=\"0311047\"})",
       "legendFormat": "temperature"
      }
     ]
    }
   ]
  }
 ]
}