global:
  scrape_interval: 5s # How frequently Prometheus will scrape the metrics

scrape_configs:
  - job_name: "kafka_consumer"
    static_configs:
      - targets: ["kafka-consumer:8000"]
  # - job_name: "og_prink_job"
  #   static_configs:
  #     - targets: ["og-prink-job:9252"]
  - job_name: "flink_job"
    static_configs:
      - targets: ["flink-job:9249"]

  - job_name: "flink_jobmanager_metrics"
    static_configs:
      - targets: ["flink-jobmanager:9249"]
  - job_name: "flink_taskmanager_metrics"
    static_configs:
      - targets: ["flink-taskmanager:9249"]
